### ISSUE TITLE
Unable to integrate with appium

### ISSUE THREAD

**Issue by ghost** [healenium/healenium-appium#29]
While running getting "no class found :type config " exception

**Comment by AnatoliZaitsau** [comment]
Could you please show stacktrace of this error

**Comment by ghost** [comment]
Aug 31, 2021 2:11:36 PM io.appium.java_client.remote.AppiumCommandExecutor$1 lambda$0
INFO: Detected dialect: W3C
Exception in thread "main" java.lang.NoSuchMethodError: com.epam.healenium.SelfHealingEngine.<init>(Ljava/lang/Object;Lcom/typesafe/config/Config;)V
	at com.epam.healenium.appium.AppiumEngine.<init>(AppiumEngine.java:50)
	at com.epam.healenium.appium.DriverWrapper.wrap(DriverWrapper.java:45)
	at com.epam.healenium.appium.DriverWrapper.wrap(DriverWrapper.java:38)
	at Automation.SelfHealingTest.Demo.main(Demo.java:48)

**Comment by AnatoliZaitsau** [comment]
Thank you for the information, we need some time to investigate

**Comment by ashish143ti** [comment]
Hi @Mitrabhanu-tech and @AnatoliZaitsau  ,

I didn't get such issue at the time of Appium integration , the major bug I have found from my end - self healing not working .

I guess you are getting this issue due to type safe (jar) version conflict issue or instead of using healenium appium 1.2 maven dependancy you have directly imported healenium appium jar in to your project, kindly use maven dependancy of healenium appium 1.2 , in case you are already using healenium appium dependancy than remove existing type safe config maven dependency or declare below dependency in pom.xml .


<dependency>
    <groupId>com.typesafe</groupId>
    <artifactId>config</artifactId>
    <version>1.4.1</version>
</dependency>

**Comment by ghost** [comment]
Thnks for your update, but my application is opeing two times while iam running

**Comment by ghost** [comment]
@ashish143ti: is your application invoking two times
