### ISSUE TITLE
Error message "New element locator have not been found. There is a lack of reference data."

### ISSUE THREAD

**Issue by lknguyen0** [healenium/healenium-appium#44]
Hi all,

in my project setup, it seems to me like the connection to the database can not be established properly. When healing should be done, I am getting the following error:
`[main] WARN com.epam.healenium.processor.HealingProcessor - New element locator have not been found. There is a lack of reference data.`
... although I ran plain tests with the correct selectors before. In Docker Desktop I can also see both of the containers (db and hlm backend) up and running. 

**Error stack:**

`at com.epam.healenium.processor.FindElementProcessor.execute(FindElementProcessor.java:24)
	at com.epam.healenium.processor.BaseProcessor.process(BaseProcessor.java:41)
	at com.epam.healenium.handlers.proxy.BaseHandler.findElement(BaseHandler.java:58)
	at com.epam.healenium.appium.handlers.proxy.MobileSelfHealingProxyInvocationHandler.invoke(MobileSelfHealingProxyInvocationHandler.java:43)`

**Docker log** (for some reason it says "received fast shutdown request" but I just ran the containers using docker-compose up -d):

`fixing permissions on existing directory /var/lib/postgresql/data ... ok

creating subdirectories ... ok

selecting default max_connections ... 100

selecting default shared_buffers ... 128MB

selecting default timezone ... UTC

selecting dynamic shared memory implementation ... posix

creating configuration files ... ok

running bootstrap script ... ok

performing post-bootstrap initialization ... ok

syncing data to disk ... ok

Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data -l logfile start

sh: locale: not found

2022-03-23 16:48:18.357 UTC [30] WARNING:  no usable system locales were found

waiting for server to start....2022-03-23 16:48:19.284 UTC [36] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"

2022-03-23 16:48:19.300 UTC [37] LOG:  database system was shut down at 2022-03-23 16:48:19 UTC

WARNING: enabling "trust" authentication for local connections

You can change this by editing pg_hba.conf or using the option -A, or

--auth-local and --auth-host, the next time you run initdb.

2022-03-23 16:48:19.311 UTC [36] LOG:  database system is ready to accept connections

 done

server started

CREATE DATABASE

/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init.sql

CREATE SCHEMA

GRANT

waiting for server to shut down...2022-03-23 16:48:19.758 UTC [36] LOG:  received fast shutdown request

.2022-03-23 16:48:19.760 UTC [36] LOG:  aborting any active transactions

2022-03-23 16:48:19.762 UTC [36] LOG:  background worker "logical replication launcher" (PID 43) exited with exit code 1

2022-03-23 16:48:19.762 UTC [38] LOG:  shutting down

2022-03-23 16:48:19.784 UTC [36] LOG:  database system is shut down

 done

server stopped

PostgreSQL init process complete; ready for start up.

2022-03-23 16:48:19.870 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432

2022-03-23 16:48:19.870 UTC [1] LOG:  listening on IPv6 address "::", port 5432

2022-03-23 16:48:19.873 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"

2022-03-23 16:48:19.884 UTC [52] LOG:  database system was shut down at 2022-03-23 16:48:19 UTC

2022-03-23 16:48:19.888 UTC [1] LOG:  database system is ready to accept connections

2022-03-23 16:48:23.686 UTC [59] ERROR:  relation "healenium.databasechangeloglock" does not exist at character 22

2022-03-23 16:48:23.686 UTC [59] STATEMENT:  SELECT COUNT(*) FROM healenium.databasechangeloglock`

**Dependencies and versions:**

- Healenium version: 1.2.3
- Healenium backend version: 3.2.1
- Appium version: 1.18.0

Any support or pointers are very much appreciated!

**Comment by lknguyen0** [comment]
I figured there was an error in my docker-compose file, which was my fault. Sorry for the inconvenience and I'm closing this issue
